# Generated by Django 2.2.6 on 2019-10-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wordfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wfile', models.FileField(upload_to='media')),
                ('fullname', models.CharField(max_length=200)),
            ],
        ),
    ]
