# Generated by Django 2.2.6 on 2019-10-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2p', '0002_auto_20191012_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordfiles',
            name='img',
            field=models.ImageField(default=0, upload_to='files'),
            preserve_default=False,
        ),
    ]
